version: '3'

services:
  redis:
    image: redis/redis-stack:7.2.0-v2
    platform: linux/arm64
    restart: always
    ports:
      - '8001:8001' # redist insight
    volumes:
      - redis_cache:/data
    environment:
      REDIS_ARGS: '--appendonly yes --aof-use-rdb-preamble yes'
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  redis_cache:
